# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agr_product',
            fields=[
                ('productid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='农产品ID')),
                ('productname', models.CharField(max_length=20, verbose_name='农产品名称')),
            ],
            options={
                'verbose_name': '农产品',
                'verbose_name_plural': '农产品',
            },
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('dateid', models.IntegerField(primary_key=True, serialize=False, verbose_name='日期ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('monthday', models.IntegerField(verbose_name='日')),
                ('weekday', models.IntegerField(null=True, verbose_name='星期几')),
            ],
            options={
                'verbose_name': '日期',
                'verbose_name_plural': '日期',
            },
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('marketid', models.IntegerField(primary_key=True, serialize=False, verbose_name='市场ID')),
                ('marketname', models.CharField(max_length=30, verbose_name='市场名称')),
            ],
            options={
                'verbose_name': '市场',
                'verbose_name_plural': '市场',
            },
        ),
        migrations.CreateModel(
            name='price_predict1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='预测价格')),
                ('sequenceid', models.IntegerField(null=True, verbose_name='序列号')),
                ('dateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期ID')),
            ],
            options={
                'verbose_name': '农产品价格预测1',
                'verbose_name_plural': '农产品价格预测1',
            },
        ),
        migrations.CreateModel(
            name='price_predict2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='预测价格')),
                ('sequenceid', models.IntegerField(null=True, verbose_name='序列号')),
                ('dateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期ID')),
            ],
            options={
                'verbose_name': '农产品价格预测2',
                'verbose_name_plural': '农产品价格预测2',
            },
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False, verbose_name='种类ID')),
                ('categoryname', models.CharField(max_length=5, verbose_name='种类名称')),
            ],
            options={
                'verbose_name': '农产品种类',
                'verbose_name_plural': '农产品种类',
            },
        ),
        migrations.CreateModel(
            name='product_in_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.market', verbose_name='市场')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.agr_product', verbose_name='农产品')),
            ],
        ),
        migrations.CreateModel(
            name='product_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期')),
                ('marketproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_in_market', verbose_name='农产品')),
            ],
            options={
                'verbose_name': '农产品价格',
                'verbose_name_plural': '农产品价格',
            },
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('provinceid', models.IntegerField(primary_key=True, serialize=False, verbose_name='省份ID')),
                ('provincename', models.CharField(max_length=20, verbose_name='省份名称')),
            ],
        ),
        migrations.AddField(
            model_name='price_predict2',
            name='marketproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_in_market', verbose_name='农产品'),
        ),
        migrations.AddField(
            model_name='price_predict1',
            name='marketproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_in_market', verbose_name='农产品'),
        ),
        migrations.AddField(
            model_name='market',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='agr_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_category', verbose_name='农产品种类'),
        ),
    ]
