# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_predict1',
            name='dateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期id'),
        ),
        migrations.AlterField(
            model_name='price_predict2',
            name='dateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期id'),
        ),
    ]
