# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-24 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190323_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price_predict1',
            old_name='dateid',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='price_predict2',
            old_name='dateid',
            new_name='date',
        ),
    ]
