# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190324_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_predict1',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期id'),
        ),
        migrations.AlterField(
            model_name='price_predict2',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.date', verbose_name='日期id'),
        ),
    ]
