# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default=None, max_length=6, null=True),
        ),
    ]
