# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavNews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addtime', models.DateTimeField(verbose_name='收藏时间')),
                ('userid', models.IntegerField(verbose_name='用户ID')),
                ('newsid', models.IntegerField(verbose_name='新闻ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
            ],
            options={
                'managed': False,
                'db_table': 'View_MyfavNews',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='news_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '新闻浏览',
                'verbose_name_plural': '新闻浏览',
            },
        ),
        migrations.CreateModel(
            name='product_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '农产品浏览',
                'verbose_name_plural': '农产品浏览',
            },
        ),
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200, verbose_name='反馈')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '新闻推荐',
                'verbose_name_plural': '新闻推荐',
            },
        ),
        migrations.CreateModel(
            name='user_fav_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '收藏新闻信息',
                'verbose_name_plural': '收藏新闻信息',
            },
        ),
        migrations.CreateModel(
            name='user_fav_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtype', models.IntegerField(default=1, verbose_name='收藏类型')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('mf1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favmf1', to='products.product_in_market', verbose_name='农产品-市场1')),
                ('mf2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favmf2', to='products.product_in_market', verbose_name='农产品-市场2')),
            ],
            options={
                'verbose_name': '收藏农产品信息',
                'verbose_name_plural': '收藏农产品信息',
            },
        ),
    ]
