# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='knearest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(verbose_name='first')),
                ('second', models.IntegerField(verbose_name='second')),
                ('third', models.IntegerField(verbose_name='third')),
                ('fourth', models.IntegerField(verbose_name='fourth')),
                ('fifth', models.IntegerField(verbose_name='fifth')),
            ],
            options={
                'verbose_name': '最近5个新闻',
                'verbose_name_plural': '最近5个新闻',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('newsid', models.IntegerField(primary_key=True, serialize=False, verbose_name='新闻ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='新闻URL')),
                ('newsdate', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('resource', models.CharField(max_length=20, null=True, verbose_name='新闻来源')),
                ('newscontent', models.TextField(default='', verbose_name='新闻主体')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='postings',
            fields=[
                ('term', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='词项')),
                ('df', models.IntegerField(verbose_name='出现频数')),
                ('docs', models.TextField(verbose_name='出处时间')),
            ],
            options={
                'verbose_name': '排序条件',
                'verbose_name_plural': '排序条件',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('tagid', models.IntegerField(primary_key=True, serialize=False, verbose_name='新闻模块ID')),
                ('tagname', models.CharField(max_length=5, verbose_name='新闻模块名')),
            ],
            options={
                'verbose_name': '新闻模块',
                'verbose_name_plural': '新闻模块',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='newstag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag', verbose_name='新闻模块'),
        ),
    ]
